
class UserError(Exception):
    pass

class NotFoundError(Exception):
    pass
